#!/bin/bash

# --- IMPORTANT SECURITY WARNING ---
# This script retrieves sensitive information (GitHub Secrets) and stores it
# in a local .env file. While convenient for local development, storing secrets
# locally carries inherent security risks. Ensure your local machine is secure
# and that the .env file is properly git-ignored and protected.
# DO NOT commit the .env file to your repository.
# ---

# Exit immediately if a command exits with a non-zero status.
set -e

echo "--- Syncing .env from GitHub Environment (main) ---"

# Check if 'gh' CLI is installed
if ! command -v gh &> /dev/null
then
    echo "ERROR: GitHub CLI (gh) is not installed."
    echo "Please install 'gh' to use this script. Instructions: https://github.com/cli/cli#installation"
    exit 1
fi

# Check if 'jq' is installed
if ! command -v jq &> /dev/null
then
    echo "ERROR: 'jq' is not installed."
    echo "Please install 'jq' to use this script. Instructions: https://stedolan.github.io/jq/download/"
    exit 1
fi

# Ensure user is logged into gh CLI
if ! gh auth status &> /dev/null
then
    echo "ERROR: You are not logged into GitHub CLI."
    echo "Please run 'gh auth login' to authenticate."
    exit 1
fi

# Get the GitHub repository owner and name from the current git repository
# Use 'gh repo view --json' and parse with 'jq'
REPO_INFO=$(gh repo view --json owner,name)
REPO_OWNER=$(echo "$REPO_INFO" | jq -r '.owner.login')
REPO_NAME=$(echo "$REPO_INFO" | jq -r '.name')


if [ -z "$REPO_OWNER" ] || [ -z "$REPO_NAME" ]; then
    echo "ERROR: Could not determine GitHub repository owner/name. Ensure you are in a git repository linked to GitHub."
    exit 1
fi

echo "Repository: ${REPO_OWNER}/${REPO_NAME}"
echo "GitHub Environment: main"

# Initialize or clear .env file
echo "# Generated by sync-env-from-github.sh on $(date)" > .env
echo "# DO NOT commit this file to git." >> .env
echo "" >> .env

# --- Fetch GitHub Secrets ---
echo "Fetching secrets from GitHub 'main' environment..."
gh secret list --env main --json name | jq -r '.[].name' | while read -r secret_name; do
    echo "Fetching secret: $secret_name"
    # 'gh secret get' prints the value directly to stdout.
    # Redirect stderr to /dev/null to suppress "not found" errors if a secret is listed but not accessible.
    SECRET_VALUE=$(gh secret get "$secret_name" --env main 2>/dev/null || echo "")
    if [ -n "$SECRET_VALUE" ]; then
        # Quote values to be safe
        echo "${secret_name}=\"${SECRET_VALUE}\"" >> .env
        echo "  - Added ${secret_name}"
    else
        echo "${secret_name}=" >> .env
        echo "  - WARN: Value for secret '$secret_name' not retrieved. Added as empty."
    fi
done

echo "" >> .env

# --- Fetch GitHub Variables ---
echo "Fetching variables from GitHub 'main' environment..."
gh variable list --env main --json name | jq -r '.[].name' | while read -r var_name; do
    echo "Fetching variable: $var_name"
    # 'gh variable get' prints the value directly to stdout.
    # Redirect stderr to /dev/null to suppress errors if not found.
    VAR_VALUE=$(gh variable get "$var_name" --env main 2>/dev/null || echo "")
    if [ -n "$VAR_VALUE" ]; then
        # Quote values to handle spaces and special characters
        echo "${var_name}=\"${VAR_VALUE}\"" >> .env
        echo "  - Added ${var_name}"
    else
        echo "${var_name}=" >> .env
        echo "  - WARN: Value for variable '$var_name' not retrieved. Added as empty."
    fi
done


echo ""
echo "--- .env file created/updated ---"
echo "Remember to review and fill in any missing values manually."
echo "Also, manually manage your '.dropbox.token' file."
echo "Script finished."
